# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import embedding_pb2 as app_dot_proto_dot_embedding__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/proto/embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateEmbedding = channel.unary_unary(
                '/embedding.v1.EmbeddingService/GenerateEmbedding',
                request_serializer=app_dot_proto_dot_embedding__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_embedding__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.GenerateEmbeddings = channel.unary_unary(
                '/embedding.v1.EmbeddingService/GenerateEmbeddings',
                request_serializer=app_dot_proto_dot_embedding__pb2.BatchEmbeddingRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_embedding__pb2.BatchEmbeddingResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GenerateEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=app_dot_proto_dot_embedding__pb2.EmbeddingRequest.FromString,
                    response_serializer=app_dot_proto_dot_embedding__pb2.EmbeddingResponse.SerializeToString,
            ),
            'GenerateEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbeddings,
                    request_deserializer=app_dot_proto_dot_embedding__pb2.BatchEmbeddingRequest.FromString,
                    response_serializer=app_dot_proto_dot_embedding__pb2.BatchEmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedding.v1.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('embedding.v1.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.v1.EmbeddingService/GenerateEmbedding',
            app_dot_proto_dot_embedding__pb2.EmbeddingRequest.SerializeToString,
            app_dot_proto_dot_embedding__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.v1.EmbeddingService/GenerateEmbeddings',
            app_dot_proto_dot_embedding__pb2.BatchEmbeddingRequest.SerializeToString,
            app_dot_proto_dot_embedding__pb2.BatchEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
