# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/embedding.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'app/proto/embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pp/proto/embedding.proto\x12\x0c\x65mbedding.v1\" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"H\n\x11\x45mbeddingResponse\x12\r\n\x05model\x18\x01 \x01(\t\x12\x11\n\tdimension\x18\x02 \x01(\x05\x12\x11\n\tembedding\x18\x03 \x03(\x02\"&\n\x15\x42\x61tchEmbeddingRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"i\n\x16\x42\x61tchEmbeddingResponse\x12\r\n\x05model\x18\x01 \x01(\t\x12\x11\n\tdimension\x18\x02 \x01(\x05\x12-\n\nembeddings\x18\x03 \x03(\x0b\x32\x19.embedding.v1.FloatVector\"\x1d\n\x0b\x46loatVector\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32\xc9\x01\n\x10\x45mbeddingService\x12T\n\x11GenerateEmbedding\x12\x1e.embedding.v1.EmbeddingRequest\x1a\x1f.embedding.v1.EmbeddingResponse\x12_\n\x12GenerateEmbeddings\x12#.embedding.v1.BatchEmbeddingRequest\x1a$.embedding.v1.BatchEmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=43
  _globals['_EMBEDDINGREQUEST']._serialized_end=75
  _globals['_EMBEDDINGRESPONSE']._serialized_start=77
  _globals['_EMBEDDINGRESPONSE']._serialized_end=149
  _globals['_BATCHEMBEDDINGREQUEST']._serialized_start=151
  _globals['_BATCHEMBEDDINGREQUEST']._serialized_end=189
  _globals['_BATCHEMBEDDINGRESPONSE']._serialized_start=191
  _globals['_BATCHEMBEDDINGRESPONSE']._serialized_end=296
  _globals['_FLOATVECTOR']._serialized_start=298
  _globals['_FLOATVECTOR']._serialized_end=327
  _globals['_EMBEDDINGSERVICE']._serialized_start=330
  _globals['_EMBEDDINGSERVICE']._serialized_end=531
# @@protoc_insertion_point(module_scope)
