# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/llm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'app/proto/llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pp/proto/llm.proto\x12\x03llm\"+\n\nLLMMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"Q\n\x0eSummaryRequest\x12\x18\n\x10previous_summary\x18\x01 \x01(\t\x12%\n\x0cnew_messages\x18\x02 \x03(\x0b\x32\x0f.llm.LLMMessage\"\"\n\x0fSummaryResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\"\x1e\n\x0b\x46\x61\x63tRequest\x12\x0f\n\x07summary\x18\x01 \x01(\t\"1\n\x0c\x46\x61\x63tResponse\x12!\n\x05\x66\x61\x63ts\x18\x01 \x03(\x0b\x32\x12.llm.ExtractedFact\"H\n\rExtractedFact\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x12\n\nimportance\x18\x02 \x01(\x02\x12\x11\n\tstatement\x18\x03 \x01(\t2y\n\nLLMService\x12\x36\n\tSummarize\x12\x13.llm.SummaryRequest\x1a\x14.llm.SummaryResponse\x12\x33\n\x0c\x45xtractFacts\x12\x10.llm.FactRequest\x1a\x11.llm.FactResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LLMMESSAGE']._serialized_start=28
  _globals['_LLMMESSAGE']._serialized_end=71
  _globals['_SUMMARYREQUEST']._serialized_start=73
  _globals['_SUMMARYREQUEST']._serialized_end=154
  _globals['_SUMMARYRESPONSE']._serialized_start=156
  _globals['_SUMMARYRESPONSE']._serialized_end=190
  _globals['_FACTREQUEST']._serialized_start=192
  _globals['_FACTREQUEST']._serialized_end=222
  _globals['_FACTRESPONSE']._serialized_start=224
  _globals['_FACTRESPONSE']._serialized_end=273
  _globals['_EXTRACTEDFACT']._serialized_start=275
  _globals['_EXTRACTEDFACT']._serialized_end=347
  _globals['_LLMSERVICE']._serialized_start=349
  _globals['_LLMSERVICE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
