# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import llm_pb2 as app_dot_proto_dot_llm__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/proto/llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSummary = channel.unary_unary(
                '/llm.LLMService/GenerateSummary',
                request_serializer=app_dot_proto_dot_llm__pb2.SummaryRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_llm__pb2.SummaryResponse.FromString,
                _registered_method=True)
        self.ExtractFacts = channel.unary_unary(
                '/llm.LLMService/ExtractFacts',
                request_serializer=app_dot_proto_dot_llm__pb2.FactsRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_llm__pb2.FactsResponse.FromString,
                _registered_method=True)
        self.GenerateEmbedding = channel.unary_unary(
                '/llm.LLMService/GenerateEmbedding',
                request_serializer=app_dot_proto_dot_llm__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_llm__pb2.EmbeddingResponse.FromString,
                _registered_method=True)


class LLMServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GenerateSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractFacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSummary,
                    request_deserializer=app_dot_proto_dot_llm__pb2.SummaryRequest.FromString,
                    response_serializer=app_dot_proto_dot_llm__pb2.SummaryResponse.SerializeToString,
            ),
            'ExtractFacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractFacts,
                    request_deserializer=app_dot_proto_dot_llm__pb2.FactsRequest.FromString,
                    response_serializer=app_dot_proto_dot_llm__pb2.FactsResponse.SerializeToString,
            ),
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=app_dot_proto_dot_llm__pb2.EmbeddingRequest.FromString,
                    response_serializer=app_dot_proto_dot_llm__pb2.EmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/GenerateSummary',
            app_dot_proto_dot_llm__pb2.SummaryRequest.SerializeToString,
            app_dot_proto_dot_llm__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractFacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/ExtractFacts',
            app_dot_proto_dot_llm__pb2.FactsRequest.SerializeToString,
            app_dot_proto_dot_llm__pb2.FactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/GenerateEmbedding',
            app_dot_proto_dot_llm__pb2.EmbeddingRequest.SerializeToString,
            app_dot_proto_dot_llm__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
